# Language Templates for Receipt Text
# All text elements that appear on receipts in different languages

languages:
  de:  # German
    kitchen:
      header: "KÜCHE"
      preparing: "BESTELLUNG ZUBEREITEN"
      dishes: "GERICHTE"
      preparation: "ZUBEREITUNG"
      customer: "KUNDE"
      pickup: "ABHOLUNG"
      delivery: "LIEFERUNG"
      fresh_prepare: "🔥 FRISCH ZUBEREITEN 🔥"
      special: "SPEZIELL"
      allergy_warning: "🚨 ALLERGIE WARNUNG 🚨"
      total_dishes: "Gesamt Gerichte"
      estimated_time: "Geschätzte Zeit"
      minutes: "Min"

    service:
      order_number: "BESTELLUNG"
      order_id: "ID"
      ordered_at: "Bestellt"
      pickup_time: "Abholung"
      delivery_time: "Lieferung"
      customer: "KUNDE"
      pickup_location: "ABHOLORT"
      delivery_address: "LIEFERADRESSE"
      notes: "📝 HINWEISE"
      order: "BESTELLUNG"
      total: "GESAMT"
      payment: "Zahlung"
      ready_pickup: "✅ BEREIT ZUR ABHOLUNG ✅"
      start_delivery: "🚀 LIEFERUNG STARTEN 🚀"

    customer:
      invoice: "KUNDENRECHNUNG"
      order_id_label: "Bestell-ID"
      date: "Datum"
      time: "Zeit"
      service: "Service"
      customer: "KUNDE"
      pickup: "ABHOLUNG"
      delivery_address: "LIEFERADRESSE"
      order: "BESTELLUNG"
      article: "Artikel"
      qty: "Anz"
      subtotal: "Zwischensumme"
      vat: "MwSt"
      total: "GESAMT"
      payment_method: "Zahlungsart"
      status: "Status"
      thank_you: "Vielen Dank für Ihren Besuch!"
      tax_info: "Steuerliche Angaben"

    common:
      phone: "Tel"
      email: "Email"
      paid: "Bezahlt"
      open: "Offen"
      cash_on_pickup: "Bar bei Abholung"
      cash_on_delivery: "Bar bei Lieferung"
      online_payment: "Online bezahlt"

  en:  # English
    kitchen:
      header: "KITCHEN"
      preparing: "PREPARE ORDER"
      dishes: "DISHES"
      preparation: "PREPARATION"
      customer: "CUSTOMER"
      pickup: "PICKUP"
      delivery: "DELIVERY"
      fresh_prepare: "🔥 PREPARE FRESH 🔥"
      special: "SPECIAL"
      allergy_warning: "🚨 ALLERGY WARNING 🚨"
      total_dishes: "Total Dishes"
      estimated_time: "Estimated Time"
      minutes: "Min"

    service:
      order_number: "ORDER"
      order_id: "ID"
      ordered_at: "Ordered"
      pickup_time: "Pickup"
      delivery_time: "Delivery"
      customer: "CUSTOMER"
      pickup_location: "PICKUP LOCATION"
      delivery_address: "DELIVERY ADDRESS"
      notes: "📝 NOTES"
      order: "ORDER"
      total: "TOTAL"
      payment: "Payment"
      ready_pickup: "✅ READY FOR PICKUP ✅"
      start_delivery: "🚀 START DELIVERY 🚀"

    customer:
      invoice: "CUSTOMER RECEIPT"
      order_id_label: "Order ID"
      date: "Date"
      time: "Time"
      service: "Service"
      customer: "CUSTOMER"
      pickup: "PICKUP"
      delivery_address: "DELIVERY ADDRESS"
      order: "ORDER"
      article: "Item"
      qty: "Qty"
      subtotal: "Subtotal"
      vat: "VAT"
      total: "TOTAL"
      payment_method: "Payment Method"
      status: "Status"
      thank_you: "Thank you for your visit!"
      tax_info: "Tax Information"

    common:
      phone: "Tel"
      email: "Email"
      paid: "Paid"
      open: "Open"
      cash_on_pickup: "Cash on Pickup"
      cash_on_delivery: "Cash on Delivery"
      online_payment: "Online Payment"

  fr:  # French
    kitchen:
      header: "CUISINE"
      preparing: "PRÉPARER COMMANDE"
      dishes: "PLATS"
      preparation: "PRÉPARATION"
      customer: "CLIENT"
      pickup: "À EMPORTER"
      delivery: "LIVRAISON"
      fresh_prepare: "🔥 PRÉPARER FRAIS 🔥"
      special: "SPÉCIAL"
      allergy_warning: "🚨 ALERTE ALLERGIE 🚨"
      total_dishes: "Total Plats"
      estimated_time: "Temps Estimé"
      minutes: "Min"

    service:
      order_number: "COMMANDE"
      order_id: "ID"
      ordered_at: "Commandé"
      pickup_time: "À emporter"
      delivery_time: "Livraison"
      customer: "CLIENT"
      pickup_location: "LIEU DE RETRAIT"
      delivery_address: "ADRESSE LIVRAISON"
      notes: "📝 NOTES"
      order: "COMMANDE"
      total: "TOTAL"
      payment: "Paiement"
      ready_pickup: "✅ PRÊT À EMPORTER ✅"
      start_delivery: "🚀 COMMENCER LIVRAISON 🚀"

    customer:
      invoice: "REÇU CLIENT"
      order_id_label: "ID Commande"
      date: "Date"
      time: "Heure"
      service: "Service"
      customer: "CLIENT"
      pickup: "À EMPORTER"
      delivery_address: "ADRESSE LIVRAISON"
      order: "COMMANDE"
      article: "Article"
      qty: "Qté"
      subtotal: "Sous-total"
      vat: "TVA"
      total: "TOTAL"
      payment_method: "Mode Paiement"
      status: "Statut"
      thank_you: "Merci pour votre visite!"
      tax_info: "Informations Fiscales"

    common:
      phone: "Tél"
      email: "Email"
      paid: "Payé"
      open: "Ouvert"
      cash_on_pickup: "Espèces à emporter"
      cash_on_delivery: "Espèces à livraison"
      online_payment: "Paiement en ligne"

  it:  # Italian
    kitchen:
      header: "CUCINA"
      preparing: "PREPARARE ORDINE"
      dishes: "PIATTI"
      preparation: "PREPARAZIONE"
      customer: "CLIENTE"
      pickup: "RITIRO"
      delivery: "CONSEGNA"
      fresh_prepare: "🔥 PREPARARE FRESCO 🔥"
      special: "SPECIALE"
      allergy_warning: "🚨 AVVISO ALLERGIA 🚨"
      total_dishes: "Totale Piatti"
      estimated_time: "Tempo Stimato"
      minutes: "Min"

    service:
      order_number: "ORDINE"
      order_id: "ID"
      ordered_at: "Ordinato"
      pickup_time: "Ritiro"
      delivery_time: "Consegna"
      customer: "CLIENTE"
      pickup_location: "LUOGO RITIRO"
      delivery_address: "INDIRIZZO CONSEGNA"
      notes: "📝 NOTE"
      order: "ORDINE"
      total: "TOTALE"
      payment: "Pagamento"
      ready_pickup: "✅ PRONTO PER RITIRO ✅"
      start_delivery: "🚀 INIZIA CONSEGNA 🚀"

    customer:
      invoice: "RICEVUTA CLIENTE"
      order_id_label: "ID Ordine"
      date: "Data"
      time: "Ora"
      service: "Servizio"
      customer: "CLIENTE"
      pickup: "RITIRO"
      delivery_address: "INDIRIZZO CONSEGNA"
      order: "ORDINE"
      article: "Articolo"
      qty: "Qta"
      subtotal: "Subtotale"
      vat: "IVA"
      total: "TOTALE"
      payment_method: "Metodo Pagamento"
      status: "Stato"
      thank_you: "Grazie per la visita!"
      tax_info: "Informazioni Fiscali"

    common:
      phone: "Tel"
      email: "Email"
      paid: "Pagato"
      open: "Aperto"
      cash_on_pickup: "Contanti al ritiro"
      cash_on_delivery: "Contanti alla consegna"
      online_payment: "Pagamento online"

  es:  # Spanish
    kitchen:
      header: "COCINA"
      preparing: "PREPARAR PEDIDO"
      dishes: "PLATOS"
      preparation: "PREPARACIÓN"
      customer: "CLIENTE"
      pickup: "RECOGER"
      delivery: "ENTREGA"
      fresh_prepare: "🔥 PREPARAR FRESCO 🔥"
      special: "ESPECIAL"
      allergy_warning: "🚨 AVISO ALERGIA 🚨"
      total_dishes: "Total Platos"
      estimated_time: "Tiempo Estimado"
      minutes: "Min"

    service:
      order_number: "PEDIDO"
      order_id: "ID"
      ordered_at: "Pedido"
      pickup_time: "Recoger"
      delivery_time: "Entrega"
      customer: "CLIENTE"
      pickup_location: "LUGAR RECOGIDA"
      delivery_address: "DIRECCIÓN ENTREGA"
      notes: "📝 NOTAS"
      order: "PEDIDO"
      total: "TOTAL"
      payment: "Pago"
      ready_pickup: "✅ LISTO PARA RECOGER ✅"
      start_delivery: "🚀 INICIAR ENTREGA 🚀"

    customer:
      invoice: "RECIBO CLIENTE"
      order_id_label: "ID Pedido"
      date: "Fecha"
      time: "Hora"
      service: "Servicio"
      customer: "CLIENTE"
      pickup: "RECOGER"
      delivery_address: "DIRECCIÓN ENTREGA"
      order: "PEDIDO"
      article: "Artículo"
      qty: "Cant"
      subtotal: "Subtotal"
      vat: "IVA"
      total: "TOTAL"
      payment_method: "Método Pago"
      status: "Estado"
      thank_you: "¡Gracias por su visita!"
      tax_info: "Información Fiscal"

    common:
      phone: "Tel"
      email: "Email"
      paid: "Pagado"
      open: "Abierto"
      cash_on_pickup: "Efectivo al recoger"
      cash_on_delivery: "Efectivo en entrega"
      online_payment: "Pago en línea"